using System;

namespace ACadSharp.Blocks
{
	/// <summary>
	/// Block-type flags (bit-coded values, may be combined).
	/// </summary>
	[Flags]
	public enum BlockTypeFlags
	{
		/// <summary>
		/// None
		/// </summary>
		None = 0,

		/// <summary>
		/// This is an anonymous block generated by hatching, associative dimensioning, other internal operations, or an application.
		/// </summary>
		Anonymous = 1,

		/// <summary>
		/// This block has non-constant attribute definitions
		/// (this bit is not set if the block has any attribute definitions that are constant, or has no attribute definitions at all).
		/// </summary>
		NonConstantAttributeDefinitions = 2,

		/// <summary>
		/// This block is an external reference.
		/// </summary>
		XRef = 4,

		/// <summary>
		/// This block is an external reference overlay.
		/// </summary>
		XRefOverlay = 8,

		/// <summary>
		/// This block is externally dependent.
		/// </summary>
		XrefDependent = 16,

		/// <summary>
		/// This is a resolved external reference, or dependent of an external reference (ignored on input).
		/// </summary>
		XrefResolved = 32,

		/// <summary>
		/// This definition is a referenced external reference (ignored on input).
		/// </summary>
		Referenced = 64
	}
}
