namespace ACadSharp.Entities.ProxyGraphics;

public enum GraphicsType
{
	Unknown = 0,
	Extents = 1,
	Circle = 2,
	CirclePt3 = 3,
	CircularArc = 4,
	CircularArc3Pt = 5,
	Polyline = 6,
	Polygon = 7,
	Mesh = 8,
	Shell = 9,
	Text = 10,
	Text2 = 11,
	XLine = 12,
	Ray = 13,
	SubentColor = 14,
	SubentLayer = 16,
	SubentLineType = 18,
	SubentMarker = 19,
	SubentFillon = 20,
	SubentTrueColor = 22,
	SubentLineWeight = 23,
	SubentLineTypeScale = 24,
	SubentThickness = 25,
	SubentPlotStyleName = 26,
	PushClip = 27,
	PopClip = 28,
	PushModelTransform = 29,
	PushModelTransform2 = 30,
	PophModelTransform = 31,
	PolylineWithNormal = 32,
	LwPolyine = 33,
	SubEntityMaterial = 34,
	SubEntityMapper = 35,
	UnicodeText = 36,
	Unknown37 = 37,
	UnicodeText2 = 38,//No code specified
}
