name: Auto Version

on:
  # push:
  #   branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  minor:
    if: ${{ github.event.label.name == 'minor' }}
    runs-on: windows-latest
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: true
      - uses: cardinalby/export-env-action@v2
        with:
          envFile: 'github.env'
      - name: Update major version
        id: '*.*.^'
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: ./src/ACadSharp/ACadSharp.csproj
          version: bump-build
      - name: Push changes
        run: ./push-changes.sh
        shell: bash
        env:
          VERSION: ${{steps.bump.outputs.newVersion}}
  major:
    if: ${{ github.event.label.name == 'major' }}
    runs-on: windows-latest
    name: Build and bump version
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          submodules: true
      - uses: cardinalby/export-env-action@v2
        with:
          envFile: 'github.env'
      - name: Update major version
        id: '*.^.0'
        uses: vers-one/dotnet-project-version-updater@v1.7
        with:
          file: ./src/ACadSharp/ACadSharp.csproj
          version: bump-build
      - name: Push changes
        run: ./push-changes.sh
        shell: bash
        env:
          VERSION: ${{steps.bump.outputs.newVersion}}
