name: Build&Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.x', '6.0.x' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with: 
        submodules: true

    - name: load vars
      uses: cardinalby/export-env-action@v2
      with:
        envFile: 'github.env'

    - name: Setup dotnet ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Build and test
      run: dotnet restore
    - name: build
      run: dotnet build --configuration Release --no-restore --framework net5.0
    - name: test
      run: dotnet test --configuration Release --no-build --verbosity normal --framework net5.0
