name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Restore dependencies and Build
      working-directory: src
      run: |
          dotnet restore
          dotnet build --configuration Release --no-restore